### ISSUE TITLE
Error while setting up espsomfy_rts platform for cover

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS-HA#10]
Hello.

I got the following error at startup:

> Logger: homeassistant.components.cover
> Source: custom_components/espsomfy_rts/controller.py:304 
> Integration: Cover (documentation, issues) 
> First occurred: 22:07:35 (1 occurrences) 
> Last logged: 22:07:35
> 
> Error while setting up espsomfy_rts platform for cover
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/espsomfy_rts/cover.py", line 54, in async_setup_entry
>     for shade in controller.api.shades:
>   File "/config/custom_components/espsomfy_rts/controller.py", line 304, in shades
>     return self._config["shades"]
> KeyError: 'shades'

**Comment by rstrouse** [comment]
This key will be checked on the next release.

**Comment by rstrouse** [comment]
This was fixed a while ago.
