### ISSUE TITLE
Disabled Buttons (mixed usage)

### ISSUE THREAD

**Issue by Jumperm** [rstrouse/ESPSomfy-RTS-HA#11]
I have a Problem with the Homeassistant Integration.

Everything works fine until I use the normal Remote. Cause I get no feedback of the shade the position is unknown. Now I use Homeassistant to open the shade. After it's open I close it by remote. Now I can't open it again in Homeassistant because the arrow button to open it is disabled.

Is it possible to not disable the button?

<img width="500" alt="Bildschirmfoto 2023-06-04 um 17 38 29" src="https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/6853816/0c0e4d81-0f3d-4cb3-8256-29eb1c5536f0">

**Comment by rstrouse** [comment]
Did you link the remote to the shade in ESPSomfy RTS?  Unfortunately, Home Assistant does not let me determine when these buttons are enabled or disabled.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software#linking-remotes

**Comment by Jumperm** [comment]
Unfortunately, no. Shame on me.

You really do a great work. Big thanks!

**Comment by rstrouse** [comment]
Thanks for confirming
