### ISSUE TITLE
unable to set area per entity

### ISSUE THREAD

**Issue by vadercent** [rstrouse/ESPSomfy-RTS-HA#13]
Hi, first of all I want to thank you for this wonderful project! 
Once I had the hardware components in, I had it up and running in a couple of hours.  Great work!!

One question though: I noticed I cannot set the area per entity, it seems this only works on a device level. 
As my covers (shades) are on windows in different rooms, and I suppose this is like that with most people, I find this odd.
Is there a solution or workaround for this?

Or can this only work when the covers (shades) would be created as individual devices?

Br, Tim

**Comment by vadercent** [comment]
additional question: or can this only work when the covers (shades) would be created as individual devices?

**Comment by rstrouse** [comment]
You should be able to go into the shade entity and click the settings tab.  Then expand the advanced settings.
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/47839015/606c6092-4ef2-4ec2-b1f6-c55e3bb27c66)

**Comment by vadercent** [comment]
You are right, thanks for the tip!
