### ISSUE TITLE
Send event infos to HA

### ISSUE THREAD

**Issue by Pulpyyyy** [rstrouse/ESPSomfy-RTS-HA#14]
Hello

Does anyone thought of using events detected by the ESP's application to propagate them to HA (send cover ID + remote ID + key ID) ?
For example, it could be used as a trigger in an automation: kind of human overlap/bypass.

Regards

**Comment by rstrouse** [comment]
There are a full set of services in the integration for control.  I haven't messed around with the events but they are all the ones that are available to the cover domain.

**Comment by Pulpyyyy** [comment]
Hello,

Normally, HA manages the shutter's position (heatwave, heliotropy, open in the morning, close in the evening). There are even a few comfort options for watching TV: in short, everything in automatic mode.

Now that the position of the shutters is always synchronized with the actual position (which wasn't the case with my rfxcom box), I'm very happy.

I'm now thinking of disabling automatic management of individually shutters, when the user has changed their position using the physical remote control (the others would still be managed in automatic mode). To do this, I'd need to be able to tell the difference between :

- pressing the physical remote control
- a call via the api

When it's a call via the api, it means HA is managing the shutters. When it's a call via the remote control, there's human intervention and so HA deactivates automatizations for this shutter.

Additionnaly, I'd need to know the identity of the shutter and, optionnaly, the command sent (up/my/down).

A simple json (which would simply be converted into an HA sensor, with attributes) like :
{
	state:"remote",
"remote_id": "1234ABCD",
	"event_key": "up",
	"timestamp": 1234567890
}
or
{
	state:"api",
"remote_id": "5678ABCD",
	"event_key": "my",
	"timestamp": 1234567890
}

Do you see what i'm mean ?

Regards

**Comment by rstrouse** [comment]
ESPSomfy RTS knows whether it triggered the movement or something else triggered its movement.  

How do you want to pull this information?  Would attributes on the HASS entity give you the function you need?  That way you would not need to have a bunch of sensors floating around and it would get tagged specifically to the target entity.  It could then also be in sync with the internal HASS clock.  I suspect that would also make the automation as simple as looking at the attribute on the entity.

**Comment by rstrouse** [comment]
There may also be some weirdness with the my command.  This is because my is also stop but I do know whether the my actually performed movement or simply stopped the motor at a position.  Most of the time the actionable key is actually a stop command being issued but perhaps I can set this to only commands that created movement.

**Comment by rstrouse** [comment]
In addition to the state data that I have added to the entities, I will also forward the events to the hass event bus.  I just need to figure out what to send.  At a minimum I think I can send the event structure you have above.

**Comment by Pulpyyyy** [comment]
Sorry for my late reply. I'll look at the version 2.0.1 and will report ASAP.
I think you last comment is quitte i have in mind. No need to have 1 sensor for 1 cover. Just 1 sensor is enough, and updated with the latest event informations

**Comment by Pulpyyyy** [comment]
Wonderfull !
Here is test automation 
```
alias: espsomfy-rts_event
description: ""
trigger:
  - platform: event
    event_type: espsomfy-rts_event
    event_data:
      source: remote
condition: []
action:
  - service: notify.notify
    data:
      title: "{{ trigger.event.data.event_key }}"
      message: >-
        Cover {{ trigger.event.data.name }} with ID {{
        trigger.event.data.entity_id }} received command {{
        trigger.event.data.command }}
mode: single
```

![Screenshot_20230709_222507_One UI Home](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/32004297/27133b9c-4ddd-41c6-964e-789ef5d6e9cc)

**Comment by Pulpyyyy** [comment]
IMO issue can be closed, as feature is working perfectly.
Many thanks !!!!

**Comment by rstrouse** [comment]
You are welcome.  Closing issue.
