### ISSUE TITLE
Platform espsomfy_rts does not generate unique IDs.

### ISSUE THREAD

**Issue by gieljnssns** [rstrouse/ESPSomfy-RTS-HA#15]
At Home-assistant startup I'm seeing this error
```
Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:607
Integration: Cover (documentation, issues)
First occurred: 13:09:12 (1 occurrences)
Last logged: 13:09:12

Platform espsomfy_rts does not generate unique IDs. ID espsomfy_105180_4 already exists - ignoring cover.zonnetent
```
<img width="468" alt="Scherm­afbeelding 2023-06-29 om 17 17 23" src="https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/17234951/671a7afb-a354-4297-94bd-0d1934b2caa7">

<img width="493" alt="Scherm­afbeelding 2023-06-29 om 17 18 13" src="https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/17234951/4c1c2a95-71db-4960-9922-f4784bce058f">

<img width="950" alt="Scherm­afbeelding 2023-06-29 om 17 18 34" src="https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/17234951/1e8dec69-70e8-4390-bfaa-0c562082bf99">

**Comment by rstrouse** [comment]
I'll look into this but this has to do with the name being used for the entity id.  If you go into the entities list you will see that there is an entity in there with the same name but likely a different id.  If you just delete that the error will go away.

**Comment by rstrouse** [comment]
I found an issue with this and will be posting an update shortly.  This has to do with the awning sun switch id.

**Comment by rstrouse** [comment]
Update to v2.0.0 for both the ESPSomfy RTS device and the integration.  This has been fixed.
