### ISSUE TITLE
Feat. Req : ESPSomfy RTS: Set My Position

### ISSUE THREAD

**Issue by Chino2264** [rstrouse/ESPSomfy-RTS-HA#18]
I miss a service asking the shades to go to the ´my’ position. 

I do this with the somfy remote wich commands every shade at once. It would be great to call such a service instead of pressing the my button ov every  shade in home assistant’s UI. 
I tried to simulate this by asking every shade to go to its position by % but it’s slow and not accurate.

**Comment by Chino2264** [comment]
My bad : the ‘stop shade’ service do the job. 

I suggest an alias or same service named ‘go to my position’ for clarity

**Comment by rstrouse** [comment]
Yes when the shade is not currently moving stop shade moves the shade to the my position.  This mirrors the Somfy functions.  If you set up groups in ESPSomfy RTS these will also allow you to change the position of any motor in the group.
