### ISSUE TITLE
Wrong_host when trying manual add esp over internet

### ISSUE THREAD

**Issue by kostas125** [rstrouse/ESPSomfy-RTS-HA#21]
Thanks for the great job @rstrouse and the team!
I'm trying to add manually the ESPSomfy-RTS device to my HA instance over the internet and I'm getting wrong_host. I use my dynamic dns and the port forwarded to the port 80 of esp. I can verify that the port is open but no luck for the HA😊.
Also when I try to access the esp from a web page over the internet I can reach the site but it's useless because it keeps loading for centuries (attached picture)
![IMG_6299](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/21076292/10eb7b62-9364-44a9-8c4f-90f40e2b7b1c)

From local access all are good!

Any help will be very welcome 
Thanks again

_Originally posted by @kostas125 in https://github.com/rstrouse/ESPSomfy-RTS-HA/issues/4#issuecomment-1702512258_

**Comment by rstrouse** [comment]
ESPSomfy RTS uses a socket on 8080 for the web interface and the rest interface is on 8081.
