### ISSUE TITLE
Jerky slider position while moving

### ISSUE THREAD

**Issue by joeloconnor-nz** [rstrouse/ESPSomfy-RTS-HA#22]
While adjusting the position using the built-in HomeAssistant cover page, the slider jumps between the target position and current position until they meet.
The state also shows closed at every position which seems to be from the integration not seeing these blinds as "Tilt only" which is a new addition to [ESPSomfy-RTS](https://github.com/rstrouse/ESPSomfy-RTS).

**Versions installed**
ESPSomfy-RTS: 2.1.5
ESPSomfy-RTS-HA: 2.1.5
HomeAssistant: 2023.9.1

https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/18236403/e1e7af16-f8ab-41e2-9c93-05c060e695cd

**Comment by rstrouse** [comment]
Please update the integration in HACS.  I am not getting this response in Home Assistant and the slider is smooth.  I suspect that the integration is out of date since the supported_features attribute is not set.  You are correct on the states though and I will have an update soon for this.

**Comment by joeloconnor-nz** [comment]
Thanks @rstrouse, would you suggest reinstalling through HACS? I am already on the latest version -[ v2.1.5](https://github.com/rstrouse/ESPSomfy-RTS-HA/releases/tag/v2.1.5)

**Comment by rstrouse** [comment]
Are you up to date with Home Assistant?  This looks like a script issue in that the percentage is properly being sent but the display is changing the slider position.  If you watch the state it counts down and up smoothly.  Either way I will have v2.1.6 in the next day or so that fixes the open/closed state for tilt only blinds.

**Comment by joeloconnor-nz** [comment]
Thanks @rstrouse, this has solved my issue about the closed state. The jerky sliders are still a problem but could be something else causing this such as one of my plugins. I can see the slider is jumping between the "target" and "current" position during movement.

Also, sorry about the delay, life became busy.
