### ISSUE TITLE
Improve moving states for tilt-only blinds

### ISSUE THREAD

**Issue by joeloconnor-nz** [rstrouse/ESPSomfy-RTS-HA#24]
Thinking about the Open/Closed state in Home Assistant cover card, could we have the tilt-only blinds show Closed at position 0 and 100 and Open for all other positions? This may also mean changing the "Opening" and "Closing" states too.
Maybe "Moving" while the target position is 1-99 and "Closing" if the target is 0 or 100.

**Comment by rstrouse** [comment]
Actually, you can have it either way although I disagree with the 0% = closed idea.  If you go into ESPSomfy RTS there is a checkbox on the blind configuration for Invert Position (expressed in % of open).

**Comment by joeloconnor-nz** [comment]
To make sure we are speaking about the same blinds, I have the tilt-only setting applied to my Venetian blinds, so I'm not sure how either 0 or 100 could be anything other than closed.

0 is 0 degrees, closed with the slats up
50 is 90 degrees, open horizontal
100 is 180 degrees, closed with the slats down

| 0=0 degrees | 50=90 degrees | 100=180 degrees |
|--------|--------|--------|
| ![IMG_3689](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/18236403/3308647e-69b8-407a-938a-fe13ab0f0f2c) | ![IMG_3690](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/18236403/af7f0dc9-4cbf-4736-85ca-f2a1631ccd90) | ![IMG_3691](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/18236403/706c055a-94c9-460a-97b2-3275ac7c2755) |

**Comment by rstrouse** [comment]
Oh I see what you are talking about.  Unfortunately that isn’t supported on the cover component.  The whole notion of open and closed is really goofy for a whole lot of the entity types.  It works for the lift on a shade and a garage door but awnings are goofy.  With those 0% is closed of all things.

I will try to see what I can do with is_open and is_closed flags but I have not been successful with the other cover types.  Changing those attributes disable the buttons.

**Comment by rstrouse** [comment]
Actually I think I may have gotten this to work so that it reflects that it is transitioning through the 50% mark to accurately reflect whether it is closing or opening.  And when it is not 0% or 100% it reflects open.   Just a bit more testing but this will be in the next release.

**Comment by rstrouse** [comment]
v2.1.9 firmware and integration has been released.  This should operate as you described.

**Comment by joeloconnor-nz** [comment]
Thank you @rstrouse, updated my Home Assistant and it works well! Nice extra with showing opening till 50% then closing thereafter.

**Comment by joneshf** [comment]
Just noticed this issue, and thanks both of you. Thank you @joeloconnor-nz for opening the issue/explaining the use case. Thank you @rstrouse for adding this behavior. It makes the Home Assistant experience way easier to understand (for my brain).
