### ISSUE TITLE
Random disconnection from device

### ISSUE THREAD

**Issue by SimonCtl** [rstrouse/ESPSomfy-RTS-HA#35]
Hi,
Everything was working fine until this morning, now it only shows "Unavailable" but I can still access ESPSomfy portal through its local IP address.
Can't find what is wrong 🧐
Thanks for your help !

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/74704575/353180a6-a944-4ba6-bce6-39f769303463)

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/74704575/2a2d18f6-481c-4e32-b7c4-04e2a82ec4a4)

**Comment by SimonCtl** [comment]
Had to delete device and re-add it to make it work again but doesn't know why...

**Comment by rstrouse** [comment]
Next time click on the reload integration.  This will tell me if HA simply stopped communicating on the socket which is what I suspect.  Is there anything related to this in the HA log.

**Comment by open1999** [comment]
Same problem with the last v2.3.2.

I reloaded integration.

For me v2.3.1 it was ok.

**Comment by rstrouse** [comment]
@SimonCtl have you set up an IP reservation in your router for ESPSomfy RTS?  It is very odd that the web interface was available yet the plugin was not receiving any data.   In v2.3.1 there was an issue where the ESP was not timing out when checking the internet for an available update but this was resolved in 2.3.2.   During this check it would wait for github to return even when it wasn't available and during this waiting period (up to 30 minutes) the HA socket would go disabled.   I have found a workaround to the limitations in the ESP32 library so that it no longer does that.

@open1999 is the web interface still available under this condition?  If it is restart HA since it looks like a socket hang.

**Comment by SimonCtl** [comment]
> @SimonCtl have you set up an IP reservation in your router for ESPSomfy RTS? It is very odd that the web interface was available yet the plugin was not receiving any data. In v2.3.1 there was an issue where the ESP was not timing out when checking the internet for an available update but this was resolved in 2.3.2. During this check it would wait for github to return even when it wasn't available and during this waiting period (up to 30 minutes) the HA socket would go disabled. I have found a workaround to the limitations in the ESP32 library so that it no longer does that.
> 
> @open1999 is the web interface still available under this condition? If it is restart HA since it looks like a socket hang.

yes I have set up an IP reservation for my ESPSomfy RTS. For now, I haven't had any linking problem between ESPSomy RTS and HomeAssistant since. I am now dealing with HA "Unable to connect to Home Assistant" loading screen 😫 Not easy to debug/read logs

**Comment by open1999** [comment]
With ESP 2.3.1 / HA 2.3.1 all ok

With ESP 2.3.2 / HA 2.3.2 or HA 2.3.3 not ok for 

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/25722103/8dbeb11f-c0d8-4cce-a64f-de5790bc0e20)

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/25722103/4dfbf8f3-d3a6-4c04-b63c-b09b4e6bde24)

It's only information for Wifi Channel/ Wifi SSID...

No problem with the shutters on HA or ESP, it's ok.

**Comment by open1999** [comment]
Ok with With ESP 2.3.3 / HA 2.3.3
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/25722103/088b53e4-5223-42de-b392-a45073b9f5d7)

**Comment by rstrouse** [comment]
I am going to close this for now.  One thing that was changed in v2.4.0 is the order in which the plugin initializes the entities.  In the past HA started the plugin and it then attempted to initialize the entities.  Unfortunately, if the ESPSomfy RTS device was not available yet the plugin would start and HA would not have registered the entities.   

When the ESPSomfy RTS device finally came online it would then establish a connection to HA but HA had already determined that the entities were not available and would not load them.  Starting in v2.4.0 the plugin now waits to initialize the entities until contact can be made with the device.   Unfortunately, I have not been able to figure out how to coerce HA to reinitialize the entities on a successful connection to the socket.  It simply throws an error in the log that it has already been initialized and cannot be done again regardless of any attempts to unload the entities, devices, or integration.

This waiting period gets around this issue.
