### ISSUE TITLE
Bug if autocheck update off

### ISSUE THREAD

**Issue by open1999** [rstrouse/ESPSomfy-RTS-HA#36]
if autocheck update is off, HA notify an update.
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/25722103/537d4995-d6a2-46db-be35-7ad8c0a8d561)

and the link is not correct https://github.com/rstrouse/ESPSomfy-RTS/releases/tag/

**Comment by rstrouse** [comment]
I'll have a look at the update entity I assume that is saying that the current installed version is v2.3.2 since there is no new version.  It should say up to date instead when it doesn't know what the current version is.

**Comment by open1999** [comment]
To reproduce:
- HA v2.3.2
- ESP v2.3.2

On ESP:
- set autocheck update to off,
- Reboot.

On HA:
- Restart HA.

Then we have the message for a new version...


If autocheck update is on, no problem.

**Comment by rstrouse** [comment]
In v2.3.3 I will fix this issue.  It turns out that I have to make the update entity unknown if the checkbox is unchecked.

**Comment by rstrouse** [comment]
When the Auto check is turned off in ESPSomfy RTS then the entity will change to an unknown state and re-enable itself when you check it again.
