### ISSUE TITLE
"Invalid flow specified" or "Unknown error occurred", even in English

### ISSUE THREAD

**Issue by Tornix242** [rstrouse/ESPSomfy-RTS-HA#37]
Hi there,

First thank you so much for this incredible work!!!

I just setted up everything. Shades a correctly behaving from the webpage.
On my side, HA integration do not work at all, even without user/password and both HA and user language settings in English.
I also tried PIN setting, without success.

I have either "Invalid flow specified" or "Unknown error occurred" on the HA integration page.

The path to setup was challenging (and of course I messed up a shade before getting working😄) but we're getting close!
I hope you ladies and gentlemen will be able to help us, and I'm willing to contribute if I can!

I'm looking forward getting it done and wish you a great day!

**Comment by rstrouse** [comment]
After you have installed the integration from HACS you must restart home assistant.  HACS used to do this automatically but it doesn't do this anymore.

**Comment by Tornix242** [comment]
Thanks for your answer.

I already tried reboot HA multiple times.
Today I also rebooted the whole VM that hosts the Debian that runs HA 2023.12.4 and HACS 1.34.0. No changes.

I just updated to HA 2024.2.1 and the behavior is the same so far.

**Comment by ctmayhew** [comment]
I am also getting the same error. 
<img width="567" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/25053083/07071fc7-2d22-4a26-9945-ab29c5c34f12">

**Comment by rstrouse** [comment]
Try to add the integration outside of discovery by clicking the add integration at the bottom right of the page.  When the page comes up enter the IP address in the host address field.

**Comment by rstrouse** [comment]
Uggh I pushed one of the files to my dev repo instead of the release.  Go to HACS and click ESPSomfy RTS.   In the upper right you will see a 3 dots menu.   Click on that and select `Redownload`.    When the screen comes up click the `Download` button.   This will refresh the files in the configuration.

After it does that restart HA and let it discover your ESPSomfy RTS.  From there it should load the proper config_flow.

**Comment by Tornix242** [comment]
Aaaaaand it works like a charm! 😄

Next step for me will be to parameter everything properly using the ESP webpage to get accurate values during movements.

**Comment by ctmayhew** [comment]
Works for me too. Thank you so much for this - having the blinds in HomeKit is great.

**Comment by rstrouse** [comment]
Cool I am going to close this out.  Have fun!
