### ISSUE TITLE
Service cover.set_current_position not available

### ISSUE THREAD

**Issue by nl0pvm** [rstrouse/ESPSomfy-RTS-HA#41]
### ESPSomfy-RTS-HA version

v2.4.1

### What happened? What did you expect to happen?

I want to use the "set_current_position" service to correct for an incorrect curtain position due to delay's caused by the command lenght and the curtain to respond. However the "set_current_position" service is not available.

### How to reproduce it (step by step)

```bash
1. give command

service: cover.set_current_position
data: 
  entity_id: cover.woonkamer_klein_raam
  position: 18

2. receive error
```

### Logs
N/A

**Comment by rstrouse** [comment]
@nl0pvm did you get this resolved?

**Comment by nl0pvm** [comment]
did not have time yet :)

**Comment by nl0pvm** [comment]
Tested; it just does not matter what YAML i use ..... Both in homeassistant.log (and the GUI) the following error is thrown:
` Error handling message: Service cover.set_current_position not found.`

**Comment by rstrouse** [comment]
I am sorry I didn't play close enough attention to your yaml above you need to be using the espsomfy_rts domain for the service.  The HA default cover does not contain a service for setting the current position.

```
service: espsomfy_rts.set_current_position
data:
  position: 93
target:
  entity_id: cover.woonkamer_klein_raam

```

**Comment by nl0pvm** [comment]
Thanks, tested, Works.

Maybe to add this example to  to the documentation at https://github.com/rstrouse/ESPSomfy-RTS-HA/wiki/Services as without you never think of using the espsomfy_rts service instead of cover. :)

**Comment by rstrouse** [comment]
Thanks that wiki needs some love.  I'll update it when I find some time.
