### ISSUE TITLE
Position in homeassistant inverse from actual position

### ISSUE THREAD

**Issue by lsowen** [rstrouse/ESPSomfy-RTS-HA#43]
The shade position in ESPSomfy-RTS is showing correctly (opened when open, closed when closed), and I have _not_ activated the "inverted" option in ESPSomfy-RTS.  However, in HA, the status is showing opposite (fully closed when fully opened), which means that the buttons do not work (ie when it is fully closed, only the "close" button is enabled, which doesn't do anything).

* ESPSomfy-RTS: `Firmware: v2.4.1`
* ESPSomfy-RTS-HA: 2.4.1

Thoughts/suggestions on where I should start looking?

**Comment by rstrouse** [comment]
What shade type do you have selected?

**Comment by rstrouse** [comment]
Is it an awning?  Closed and open on an awning is exactly opposite of a blind, shutter, or shade.  If it is an awning, when you press the up button on the remote does it retract or extend?

**Comment by rstrouse** [comment]
Unfortunately, in HA the awning object is different and in order for it to work ESPSomfy RTS has to perform gymnastics to make it work.  Try changing the Invert Position (not command) checkbox.  This will flip things around.

**Comment by lsowen** [comment]
Unfortunately, that didn't have any effect (even when removing and re-adding the hub in HA).  However, this gave me a pointer, so I updated the config in ESPSomfy RTS to treat them as a regular shade instead of an awning.

This works for me, so I can close this issue as resolved unless you have any interest in debugging further to find out why the "Invert Position" didn't have the intended impact?  (I really appreciate your help in both writing this amazing toolset and for help in diagnosing the issue)

**Comment by rstrouse** [comment]
Unfortunately, I do not want to do anything that might actually impact the awning functions.  That was such a hard thing to figure out and it finally works well with an awning.  The other one that is really odd is the Tilt Only blind which is very close to what you have.
