### ISSUE TITLE
Integration fails to load after restarting home assistant

### ISSUE THREAD

**Issue by Ay1tsMe** [rstrouse/ESPSomfy-RTS-HA#45]
After I restart home assistant, espsomfy fails to launch correctly with every blind entity showing unavailable. I have to manually reload the integration for my blinds to load correctly. From what I can see there is no error in the logs. I'm running v2.4.1 but I've had this issue since v2.2.2.

**Comment by rstrouse** [comment]
Which firmware version are you running on the device?

**Comment by Ay1tsMe** [comment]
My mistake, forgot to update the firmware. Flashing to v2.4.0 fixed the issue.
