### ISSUE TITLE
Home Assistant repository link does not work

### ISSUE THREAD

**Issue by UsefulVid** [rstrouse/ESPSomfy-RTS-HA#46]
https://my.home-assistant.io/redirect/hacs_repository/?owner=rstrouse&repository=espsomfy-rts-ha
Repository rstrouse/espsomfy-rts-ha not found

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/39967070/03fbe764-3f4f-4813-bb05-f3b07f009e90)

**Comment by rstrouse** [comment]
Are you referring to the url from this link on the homepage?

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/47839015/4de3f1ea-f51b-4ab3-8ecf-2a40383701d8)

**Comment by UsefulVid** [comment]
From here
https://github.com/rstrouse/ESPSomfy-RTS-HA

**Comment by rstrouse** [comment]
Hmm it works for me.  Have you installed the custom repo.

**Comment by UsefulVid** [comment]
> Hmm it works for me. Have you installed the custom repo.

I thought this is what the link should do?

**Comment by msauvee** [comment]
@UsefulVid You probably did not installed HACS in your Homeassistant. Try this link https://hacs.xyz/docs/user/ .

**Comment by UsefulVid** [comment]
> @UsefulVid You probably did not installed HACS in your Homeassistant. Try this link https://hacs.xyz/docs/user/ .

![Screenshot_20240319-190150](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/39967070/bdb1fac3-6f0d-45e3-b780-4f053dfc602f)
It's installed

**Comment by rstrouse** [comment]
Click on integrations then click the 3 vertical dots in the upper right corner.  From there click custom repositories and enter `https://github.com/rstrouse/ESPSomfy-RTS-HA` then select integration as the category and press add.

From then on the link will work and it will begin to detect your device.

**Comment by rstrouse** [comment]
I assume you have gotten this sorted.  I am going to close this for now.

**Comment by arkdev1** [comment]
> Click on integrations then click the 3 vertical dots in the upper right corner. From there click custom repositories and enter `https://github.com/rstrouse/ESPSomfy-RTS-HA` then select integration as the category and press add.
> 
> From then on the link will work and it will begin to detect your device.

Same problem. I have HACS installed, but neither the Blue button nor the GitHub repository link is working.

![Image](https://github.com/user-attachments/assets/47b33fe9-1bb1-4432-b89e-2328ee6e3d63)

![Image](https://github.com/user-attachments/assets/1fae7f21-cfa9-4d61-9e5b-1a87a12f10ff)

**Comment by killtux** [comment]
i got the same error and then noticed its already part of the hacs standard repository.
