### ISSUE TITLE
Firmware Displayin HA Integration

### ISSUE THREAD

**Issue by Jumperm** [rstrouse/ESPSomfy-RTS-HA#48]
The Displayed Firmware since update to 2.4.1 is not correct.

Under Device Info and in the Configuration tap.

<img width="672" alt="Bildschirmfoto 2024-03-24 um 08 46 39" src="https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/6853816/31a76aa2-c596-48b1-89ef-e2a7f0847087">

**Comment by rstrouse** [comment]
It will update when you restart HA.  The device info is loaded on startup.

**Comment by chemelli74** [comment]
@rstrouse, you can refresh the value if you want. Check what we do in Shelly integration.

**Comment by rstrouse** [comment]
Thanks I will release the change with the next version.  I have coded and test it already.
