### ISSUE TITLE
Device is continually rediscovered

### ISSUE THREAD

**Issue by eouthwaite** [rstrouse/ESPSomfy-RTS-HA#52]
Firstly, thanks as this is a brilliant project.

I have one bit of strangeness - within seconds of configuring the integration, I get a notification that it has been discovered and I get the option to configure it again:

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/4416100/c0449096-9aad-47aa-baed-5f4a3cc6dadd)

Otherwise, it works really well.

Not sure what I can add - happy to look for diagnostics or a log if directed...

**Comment by rstrouse** [comment]
That's odd.  What version of HA are you running.   The discovery uses the id stamped onto the chip to determine whether it is installed.  It does discover a using UPnP as well as zeroconfig but that really doesn't explain it.   When you click configure does it come up with an IP address filled in?

**Comment by eouthwaite** [comment]
Got it - I used the hostname rather than the ip address.
As soon as I changed it, the problem went away.

**Comment by rstrouse** [comment]
Awesome.   Glad you got it sorted.
