### ISSUE TITLE
New translation

### ISSUE THREAD

**Issue by gralfj** [rstrouse/ESPSomfy-RTS-HA#57]
hi, gonna thank you by translating to spanish, file attached
[es.json](https://github.com/rstrouse/ESPSomfy-RTS-HA/files/15138563/es.json)

**Comment by rstrouse** [comment]
Thanks I’ll get it integrated in the next release.

**Comment by gralfj** [comment]
My pleasure

**Comment by rstrouse** [comment]
@gralfj I have integrated the es.json into the project.  Thanks again for the translation!

**Comment by gralfj** [comment]
Glad to hear it!

Thank you for your awesome project.

**Comment by magarto** [comment]
How can we apply it? I have updated to 2.4.3 but I cannot find when I should change language

**Comment by rstrouse** [comment]
It should be automatic.  If you have your language for HA set to Spanish it should automatically pick it up.
