### ISSUE TITLE
Get awning status

### ISSUE THREAD

**Issue by magarto** [rstrouse/ESPSomfy-RTS-HA#61]
Is there any way to get the opened/closed/sun status of awning updated?
I would like to include it in some automations but if sun auto open is activated, I cannot get the actual status.
Thanks in advance

**Comment by rstrouse** [comment]
Are you missing the Sunny binary sensor for the shade?

**Comment by magarto** [comment]
No, there is no binary sensor, I guess.
Only these:
![Screenshot_20240512_180723_Home Assistant](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/7046240/c23181b2-6a9d-4cfa-a6f8-027fddcfdf82)

**Comment by rstrouse** [comment]
Actually it is the entity with the no sun indicator in the sensors list.  It is currently not sunny and not windy.

**Comment by magarto** [comment]
But I do not receive any update of the information 
![Screenshot_20240512_182327_Home Assistant](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/7046240/f6906966-985b-4f22-9f61-bef8a4dbbf36)

**Comment by rstrouse** [comment]
Did you link the sun sensor to the shade in ESPSomfy RTS?

**Comment by magarto** [comment]
I am not sure, I only linked the awning using the remote. But if I press the auto open/close button in Espsomfy RTS Web, it works.
![Screenshot_20240512_190634_Firefox Nightly](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/7046240/c81574ec-279a-4ddb-b437-6d9f1d22a642)

I will check tour link

**Comment by rstrouse** [comment]
Please read the link I included in the previous post.  The sun sensor must be linked to the definition of your awning in ESPSomfy RTS or it will not know when the sunny condition is triggered.  Which sun sensor do you have?

**Comment by magarto** [comment]
Sorry for not reading it before. I have linked it now (using program button in the Soliris RTS)

**Comment by rstrouse** [comment]
Awesome!  If you have any other issues please let me know.
