### ISSUE TITLE
 Requirements for espsomfy_rts not found: ['websocket-client==1.7.0']

### ISSUE THREAD

**Issue by GaaH** [rstrouse/ESPSomfy-RTS-HA#65]
Hi,

I’m using homeassistant inside a docker container, when I do a `pip list | grep websocket` it shows
```
websocket-client                 1.8.0
```

As a consequence, I cannot install the integration, it fails with the following error

```
Enregistreur: homeassistant.setup
Source: setup.py:271
S'est produit pour la première fois: 08:14:15 (1 occurrences)
Dernier enregistrement: 08:14:15

Setup failed for custom integration 'espsomfy_rts': Requirements for espsomfy_rts not found: ['websocket-client==1.7.0'].
```

Is there any reason to fix the version of `websocket-client` to 1.7.0? If no, can you please update the requirements, and if yes, can you tell me what’s the best way to make it works? (I guess I can downgrade the package manually)

**Comment by rstrouse** [comment]
No particular reason to pin it to 1.7.0 at this point other than 1.8.0 was just released last month and haven't had time to test it.

**Comment by rstrouse** [comment]
I bumped the websocket-client in the manifest.

**Comment by GaaH** [comment]
Thanks!

**Comment by rstrouse** [comment]
I am going to close this since I believe it has been sorted out.
