### ISSUE TITLE
Open/Close Shade service/entity cards not working after using set position service

### ISSUE THREAD

**Issue by ticarki** [rstrouse/ESPSomfy-RTS-HA#7]
After calling the set position service, the shade reaches the set position. If I call the 'ESPSomfy RTS: Open Shade' service or use an entity card to open it again, it sometimes works, sometimes stops at the previously set position, or does not react.

However, I can open the shade after several up-and-down calls via the ESPSomfy RTS UI.

I am still trying to determine if this issue is related to the integration or the [ESPSomfy-RTS](https://github.com/rstrouse/ESPSomfy-RTS) project.

**Comment by rstrouse** [comment]
I have tried this on my dev system and cannot replicate your issue.  Just to be sure I performed the following steps.

1. Position the shade using the Set Position service.
2. Open the shade using either the Open Shade service or a card. (I tried it repeatedly both ways).

In all instances the shade position was maintained between the ESPSomfy RTS UI and Home Assistant.  When you go to the updates tab in the ESPSomfy RTS UI what versions are you seeing for the firmware and the application.   Keep in mind Home Assistant has this crazy 100% open mindset so 100 is open and 0 is closed.  At some point I am going to write my own cover entity to get around this backwardness.

**Comment by ticarki** [comment]
Yes, these are the steps I did.

I had two different versions (Firmware: 1.5.1, Application 1.4.7). I Updated the Application to 1.5.1, and it seems to work better. However, the following issue remains:

1. I set the position of a shade to 70 using the HA service
    -  The shade moves to the set position
 
2. I use a HA card to open the shade again
    - The shade opens
    - The shade closes again to some other position ~90; the HA card and ESPSomfy RTS UI show that the shade is open.
    - I can open the shade via ESPSomfy RTS UI, but not HA, because the up button is disabled

If I use the ESPSomfy RTS UI for the second step, everything works fine

**Comment by rstrouse** [comment]
Please create a backup and post that file here.  I will try this using your complete setup.

**Comment by rstrouse** [comment]
Also lets run a little test.  With the shade in the rest position press the my button on the remote.  If the shade moves wait until it finally stops.  After it stops hold down the my button until the shade jogs.  I suspect that the position it will move to is ~90%.

If this is the case we need to sync the my positions.  To do this, first move the shade to the full open position by pressing the up button in the ESPSomfy-RTS interface.  After the shade stops, click and hold on the my button on the ESPSomfy-RTS interface until the Set My position popup appears.  Then move the slider to 10% and press the Set My Position button.

This should move the shade to 10% closed (90% open) and set the My Position on the motor.

**Comment by ticarki** [comment]
I tried to sync the My position, but the positions were not synced between HA and the IDE, when clicking up/down. Also, when I triggered the Set position HA service with 70% after syncing the position to 10% the shade stopped at 40%. I will update the ESP to your recent update an retry.


```
  5, 16,222, 32
  1,true ,  0,   1029641,WZ Rollo links      ,  0, 56,     27000,     24000,      7000,  12576556,         0,         0,         0,         0,         0,         0, 1337,    -1.00000,    -1.00000,   100.00000,     0.00000
  2,true ,  0,   1029642,WZ Rollo rechts     ,  0, 56,     25900,     23600,      7000,  16321581,         0,         0,         0,         0,         0,         0, 1352,    -1.00000,    -1.00000,   100.00000,     0.00000
  3,true ,  0,   1029643,SZ Rollo rechts     ,  0, 56,     22500,     21900,      7000,   6285356,         0,         0,         0,         0,         0,         0, 1031,    -1.00000,    -1.00000,   100.00000,     0.00000
  4,true ,  0,   1029644,SZ Rollo links      ,  0, 56,     23300,     21500,      7000,  14542892,         0,         0,         0,         0,         0,         0, 1077,    -1.00000,    -1.00000,   100.00000,     0.00000
  5,true ,  0,   1029645,B Rollo             ,  0, 56,     22100,     21290,      7000,         0,         0,         0,         0,         0,         0,         0,  374,    -1.00000,    -1.00000,   100.00000,     0.00000
  6,true ,  0,   1029646,KZ Rollo            ,  0, 56,     22500,     21470,      7000,   7146797,         0,         0,         0,         0,         0,         0, 1071,    10.00000,    -1.00000,   100.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000
255,false,  0,         0,                    ,  0,  0,     10000,     10000,      7000,         0,         0,         0,         0,         0,         0,         0,    0,    -1.00000,    -1.00000,     0.00000,     0.00000

```

**Comment by rstrouse** [comment]
Keep in mind the cover domain in Home Assistant uses percentages in percentage of open.  I know it is fundamentally nonsensical but until I get in and rewrite the cover domain, I can only complain about how ridiculous it is.  It's funny how many the shade position is backwards threads there are on the HA community.   So if you set the position to 70% using the HA set position service it will be 30% closed.

**Comment by ticarki** [comment]
Thanks for the clarification, that is really confusing! 

I also tried to sync the 'my' position as you described after upgrading to 1.5.3.

1. I click the 'my' button on the remote, wait until it stops (~90 % closed)
2. I open the shade via the IDE (0% closed)
3. I set the 'my' position to 10% via the IDE (10% closed)

Afterwards, if I close the shade (100% closed), open it, and then click the 'my' button via the IDE, the shade moves to ~90% closed, not 10 %. Is this the expected behavior?

**Comment by rstrouse** [comment]
I think the set my command is not being repeated long enough. I will publish a version of the firmware this week that will hold the set command longer.  Originally I tested it on two shades but when I tested it on my third shade the pulses didn’t last long enough.

**Comment by rstrouse** [comment]
I published v1.5.4.  This release has some fixes to the setting of the My favorite.  I have tested it across all 3 of my shades and they all set the my position properly.  It also unsets them properly.

I will be diving into the HA integration to see if I can work around the twisted mindset of percentage of open.  It just makes no sense why they would insist on that.  I might be able contort my logical mind into to making a case for a garage door but even then it should be 100% closed not 0% open.  Responses to changing that silliness have been very dismissive and even a bit overly direct whenever it is brought up in the forums.  However, I will not be defeated.

**Comment by ticarki** [comment]
Thank you! Now the syncing of positions works perfectly for all my shades. Calling the HA service to set the shade to a specific position also works fine now. I only observed one thing:

1.  In any shade position, set position via HA service to 50% -> shade moves to 50%
2. Repeat 1st step -> shade moves to the 'my' position
3. repeat 1st step -> shade remains at the 'my' position

Both the HA UI elements and the ESPSomfy UI show that the position of the shades is at 50%, although it is at the 'my' position after the 1st step.

**Comment by rstrouse** [comment]
That is because the set target is seeking and it sends a stop command.  Unfortunately, Somfy translates that as move to my position.  I will see what I can do to filter that out.

**Comment by rstrouse** [comment]
If you update to v1.6.1 ESPSomfy-RTS will not issue a stop command if the target is the same as the current position.  This means it will not move to the my position on the second command.

**Comment by rstrouse** [comment]
Closing this as it should be resolved.
