### ISSUE TITLE
Exclamation mark on homepage

### ISSUE THREAD

**Issue by heartkingz** [rstrouse/ESPSomfy-RTS-HA#72]
I just discovered a exclamation mark on the icon of the awning on the homepage of the software. The awning works just fine, no issues. 
What does this mean? 

Thanks! 

![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/44269589/06f05397-fc15-4ae8-97c6-7ae48ae38ee7)

**Comment by rstrouse** [comment]
That is a windy warning.  Do you have a wind sensor?  If not go back into the Virtual Remote and send a Sensor command without either the sun or wind options checked.

**Comment by heartkingz** [comment]
No wind sensor attached but your suggestion solved it. Thanks!
