### ISSUE TITLE
Cover issue when adjusting range via Alexa

### ISSUE THREAD

**Issue by polmum** [rstrouse/ESPSomfy-RTS-HA#74]
Hey!
First of all, thanks for creating this awesome integration.

I added covers to Home Assistant without an issue. I can see the entities, open/close them, set them to a position, etc. 
What happened is that I added the Alexa integration and exposed the covers to it. The absolute commands, like opening and setting to a position work fine. But the adjustRange command is failing. [This](https://github.com/home-assistant/core/blob/91201155776a3c648b5f5221991145601c73e0cb/homeassistant/components/alexa/handlers.py#L1516) is a link to the link that is failing in the home assistant integration code. The log error is:
```
Received Alexa Smart Home request: {'directive': {'header': {'messageId': 'a5cd0033-234b-482a-968a-45d67a32f0e7', 'namespace': 'Alexa.RangeController', 'name': 'AdjustRangeValue', 'payloadVersion': '3', 'correlationToken': '**REDACTED**', 'instance': 'cover.position'}, 'endpoint': {'scope': {'type': 'BearerToken', 'token': '**REDACTED**'}, 'endpointId': 'cover#blackout', 'cookie': {}}, 'payload': {'rangeValueDelta': -10.0, 'rangeValueDeltaDefault': False}}}
Request Alexa.RangeController/AdjustRangeValue error INVALID_VALUE: Unable to determine cover.blackout current position
```

It appeas to be failing because it cannot determine the current position to adjust it correctly. Is it possible that that value is not being exposed in your integration code? Or could this be a home assistant issue?

Thanks!

**Comment by rstrouse** [comment]
I’ll have a look at the code for Alexa but what I don’t understand is why it does that ridiculous dance with the delta position.  Aren’t you just trying to set it to a specified percentage.  Of course the current position is reported but it could be yet another property of the cover entity that is undocumented.

**Comment by x3mpablom** [comment]
I understand that the delta position is sent when the command used with Alexa is something like "raise the cover by 10%" or "lower it a little". It would be easier if Amazon did the calculations themselves and just sent the target position, but that would not be the case.

**Comment by rstrouse** [comment]
It looks like the Alexa component does not use the property decorator for the current lift or tilt position.  I will have something for you to try shortly.

**Comment by rstrouse** [comment]
Try the release I just released.  While I do not use Alexa I traced through the code to find where the position data is coming from and made changes to set that value.

**Comment by polmum** [comment]
Hey!
I just tried it out and I got the same error in the logs.
Just FYI, I tried reporting the issue to home assistant, in case it was something on their side Apparently it was, and they already have a [PR](https://github.com/home-assistant/core/pull/121798#issue-2403821717) fixing it.
