### ISSUE TITLE
fan.FanEntityFeature missing

### ISSUE THREAD

**Issue by duts-ke** [rstrouse/ESPSomfy-RTS-HA#75]
Hi,

I was cleaning up my config for unused entities using Watchman and saw:
```
- id: fan.FanEntityFeature
  state: missing
  friendly_name: ''
  occurrences: custom_components/espsomfy_rts/services.yaml:225,235
```

Is this feature needed for the backup and reboot service?

**Comment by chemelli74** [comment]
Currently you need to exclude services.yank from watchman checks as those are just examples.

There is a PR open by me about this in the integration repo.

**Comment by duts-ke** [comment]
Ok. Thanks for the feedback. I'll close this issue as the issue is on the side of Watchman.
ref to the issue at watchman: dummylabs/thewatchman#130

and [link](https://github.com/dummylabs/thewatchman?tab=readme-ov-file#ignored-entities-and-services-option-example) to exclusion settings for anyone else seeing the same error
