### ISSUE TITLE
The state class '' of this entity is not supported.

### ISSUE THREAD

**Issue by greenbus4** [rstrouse/ESPSomfy-RTS-HA#77]
Hi,

ESPSomfy RTS Integration v2.4.7
Firmware: v2.4.6

Updated for right sensor...

My /developer-tools/statistics is reporting "The state class '' of this entity is not supported." for `sensor.wifi_channel`. Does that sensor need a state_class?

Also, did I set up the integration incorrectly since the entities are generically named w/o the device name? I.e. "`sensor.wifi_ssid`", "`sensor.hostname`".

<img width="533" alt="image" src="https://github.com/user-attachments/assets/848142e1-b336-4f3e-86c5-6f594fb1763c">

Thanks,

**Comment by rstrouse** [comment]
It shouldn’t need a state class.  Do you need the long term statistics?  HA forum has lots of similar items regarding the changes to long term statistics.

**Comment by greenbus4** [comment]
No, I don't need the statistics. I was cleaning up the issues on the statistics page and just noticed that message.  Didn't think it through.
